# Generated by Django 2.2.3 on 2020-04-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='userdata',
        ),
    ]
