# Generated by Django 3.0.5 on 2020-04-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='codechef',
            field=models.URLField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='codeforces',
            field=models.URLField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='github',
            field=models.URLField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='hackerearth',
            field=models.URLField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='hackerrank',
            field=models.URLField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='handle',
            field=models.TextField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='institute',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='linkedin',
            field=models.URLField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='spoj',
            field=models.URLField(blank=True, default='', unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
