# Generated by Django 3.0.5 on 2020-04-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200412_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='codechef',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='codeforces',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='hackerearth',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='hackerrank',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='spoj',
            field=models.URLField(blank=True, default=''),
        ),
    ]
