# Generated by Django 3.0.5 on 2020-05-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200422_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='codechefRating',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='codeforcesRating',
            field=models.TextField(default=0),
        ),
    ]
