# Generated by Django 3.0.5 on 2020-05-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200529_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeforcesRating', models.TextField(blank=True, default=0)),
                ('codechefRating', models.TextField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='codechefRating',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='codeforcesRating',
        ),
    ]
