# Generated by Django 3.0.5 on 2020-05-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200529_0541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiData',
        ),
        migrations.AddField(
            model_name='userdata',
            name='codechefRating',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='codeforcesRating',
            field=models.TextField(blank=True, default=0),
        ),
    ]
