# Generated by Django 3.0.5 on 2020-05-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('codeforcesRating', models.TextField()),
                ('codechefRating', models.TextField()),
            ],
        ),
    ]
