# Generated by Django 3.0.5 on 2020-05-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiData',
        ),
    ]
