# Generated by Django 3.1 on 2020-08-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_delete_apidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('rating', models.TextField(blank=True, default=0)),
            ],
        ),
    ]
